spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-basic.cohrr9gdkixc.ap-southeast-2.rds.amazonaws.com:3306/testdb4?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: hellsong

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update

      #show_sql: true
      #format_sql: true
    generate-ddl: true
    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
logging:
  level:
    com.jpa.student: debug
    #org.hibernate.SQL: debug
    #org.hibernate.type: trace
server:
  port: 8085
  servlet:
    encoding:
      force-response: true

      spring:
        thymeleaf:
          prefix: classpath:/templates/

